import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Layout from '@/components/Layout';
import { Button } from '@/components/ui/Button';
import { protectedRoute } from '@/utils/routes';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Wishlist</h1>
        <Button>
          <Link href="/api/auth/signout">Log out</Link>
        </Button>
      </Layout>
    </>
  );
};

export const getServerSideProps = protectedRoute();

export default Home;
